backend:
  name: git-gateway
  branch: main
media_folder: "/images"
public_folder: "/images"

collections:
  - name: "intro"
    label: "Intro Section"
    files:
      - label: "Intro Content"
        name: "intro"
        file: "_data/intro.json" # Points directly to the file
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

