backend:
  name: git-gateway
  branch: main
media_folder: "/images"
public_folder: "/images"

collections:
  - name: "intro"  # This corresponds to the content section you want to edit.
    label: "Intro Section"
    folder: "_data/intro"  # This is where the editable content will be stored.
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
